import argparse
import json
import os
import sys

import numpy as np
import torch
from torch_geometric.data import Data

sys.path.append(os.path.join(os.path.dirname(__file__), "src"))
from evopoint_da.data.components import StructureParser, build_knn_edges
from evopoint_da.models.module import EvoPointLitModule


def get_args():
    p = argparse.ArgumentParser(description="Predict Δr with conformal reject option.")
    p.add_argument("--pdb_file", required=True)
    p.add_argument("--feature_pt", required=True, help="Prepared graph feature file with x tensor.")
    p.add_argument("--ckpt_path", required=True)
    p.add_argument("--conformal_stats", required=True, help="JSON file generated by scripts/eval_run.py")
    p.add_argument("--reject_threshold", type=float, default=5.0, help="Reject if qhat exceeds this threshold")
    p.add_argument("--k", type=int, default=16)
    p.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    return p.parse_args()


def main():
    args = get_args()
    parser = StructureParser()
    parsed = parser.parse_ca_structure(args.pdb_file)
    if not parsed:
        raise ValueError("Failed to parse input structure")

    feat = torch.load(args.feature_pt, weights_only=False)
    pos = torch.tensor(parsed["coords"], dtype=torch.float32)
    x = feat["x"].float()[: len(pos)]

    edge_index, edge_attr = build_knn_edges(pos, k=args.k)
    data = Data(x=x, pos=pos, edge_index=edge_index, edge_attr=edge_attr).to(args.device)

    model = EvoPointLitModule.load_from_checkpoint(args.ckpt_path, map_location=args.device)
    model.eval().to(args.device)

    with open(args.conformal_stats, "r", encoding="utf-8") as f:
        stats = json.load(f)
    qhat = float(stats["qhat"])

    with torch.no_grad():
        delta = model(data)
    pred_norm = torch.norm(delta, dim=-1).detach().cpu().numpy()

    reject = qhat > args.reject_threshold
    if reject:
        safe_center = pos.cpu().numpy()
        safe_radius = qhat
        print(f"REJECT: qhat={qhat:.4f} > threshold={args.reject_threshold:.4f}; keeping original structure")
    else:
        safe_center = (pos + delta).detach().cpu().numpy()
        safe_radius = qhat
        print(f"ACCEPT: qhat={qhat:.4f}; returning predicted structure with conformal safety sphere")

    print(f"Mean |Δr_pred|: {pred_norm.mean():.4f}")
    print(f"Safety sphere radius (qhat): {safe_radius:.4f}")
    print(f"First 5 centers:\n{safe_center[:5]}")


if __name__ == "__main__":
    main()
